language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
install:
  - pip install --upgrade pytest
  - pip install pytest-cov codecov
script:
  - pytest --cov=stanfordkarel --cov-report= --durations=0
after_success:
  - codecov
